apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lw44i0xqo-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lw44i0xqo-java-quarkus-gitops